var rawData = `
Cosmetics for Reaper...
        ACHIEVEMENT (4 items)
                Pixel (Common Spray)
                Cute (Common Spray)
                GOLDEN (Common Weapon Skin)
                Blackwatch Reyes (Legendary Skin)
        STANDARD_COMMON (7 items)
                Heroic (Common Victory Pose)
                Heroic (Common Heroic Intro)
                RANDOM (Common Heroic Intro)
                CLASSIC (Common Weapon Skin)
                Classic (Common Skin)
                What are you looking at (Common Voice Line)
                Heroic (Common Emote)
        COMMON (57 items)
                Reaper (Rare Icon)
                Soul (Rare Icon)
                Emblem (Rare Icon)
                Slice (Epic Emote)
                Slow Clap (Epic Emote)
                Not Impressed (Epic Emote)
                Cackle (Epic Emote)
                Take a knee (Epic Emote)
                Enigmatic (Rare Victory Pose)
                Menacing (Rare Victory Pose)
                Casual (Rare Victory Pose)
                Executioner (Epic Heroic Intro)
                SHADOW STEP (Epic Heroic Intro)
                Death Blossom (Epic Heroic Intro)
                Dead man walking (Common Voice Line)
                Next (Common Voice Line)
                Haven't I killed you (Common Voice Line)
                Too easy (Common Voice Line)
                Was that all? (Common Voice Line)
                Give me a break (Common Voice Line)
                Psychopath (Common Voice Line)
                Seen a ghost? (Common Voice Line)
                If it lives, I can kill it (Common Voice Line)
                I'm back in black (Common Voice Line)
                Royal (Rare Skin)
                Blood (Rare Skin)
                Midnight (Rare Skin)
                Moss (Rare Skin)
                Desert (Epic Skin)
                Wight (Epic Skin)
                Mariachi (Legendary Skin)
                El Blanco (Legendary Skin)
                Nevermore (Legendary Skin)
                Plague Doctor (Legendary Skin)
                Icon (Common Spray)
                Psst (Common Spray)
                Everywhere (Common Spray)
                Revenge (Common Spray)
                Soul Globe (Common Spray)
                Oops (Common Spray)
                Blossom (Common Spray)
                Shadow (Common Spray)
                Cloaked (Common Spray)
                Blackwatch (Common Spray)
                Hooded (Common Spray)
                Death Blossom (Common Spray)
                Shadow Step (Common Spray)
                Scythes (Common Spray)
                Grave (Common Spray)
                Silent (Common Spray)
                Reaping (Common Spray)
                Death Comes (Common Spray)
                Time to Kill (Common Spray)
                Die Die Die (Common Spray)
                Reap On (Common Spray)
                Hellfire (Common Spray)
                Horns (Common Spray)
        SUMMER_GAMES_2016 (4 items)
                BMX (Rare Icon)
                BMX (Common Spray)
                It's in the refrigerator (Common Voice Line)
                Medal (Rare Victory Pose)
        HALLOWEEN_2016 (6 items)
                Trick or Treat (Common Spray)
                Pumpkin (Legendary Skin)
                Eternal Rest (Epic Heroic Intro)
                R.I.P. (Rare Victory Pose)
                The Reaper (Rare Icon)
                I work the graveyard shift (Common Voice Line)

Cosmetics for Zarya...
        ACHIEVEMENT (3 items)
                Pixel (Common Spray)
                Cute (Common Spray)
                GOLDEN (Common Weapon Skin)
        STANDARD_COMMON (7 items)
                Heroic (Common Victory Pose)
                Heroic (Common Heroic Intro)
                RANDOM (Common Heroic Intro)
                CLASSIC (Common Weapon Skin)
                Classic (Common Skin)
                Strong as the mountain (Common Voice Line)
                Heroic (Common Emote)
        COMMON (57 items)
                Zarya (Rare Icon)
                Particle Barrier (Rare Icon)
                512 (Rare Icon)
                Pumping Iron (Epic Emote)
                Bring It On (Epic Emote)
                Crush You (Epic Emote)
                Comedy gold (Epic Emote)
                Take a Knee (Epic Emote)
                Casual (Rare Victory Pose)
                Flexing (Rare Victory Pose)
                Check out this gun (Rare Victory Pose)
                This Is Strength (Epic Heroic Intro)
                DEADLIFT (Epic Heroic Intro)
                Maximum Charge (Epic Heroic Intro)
                Need personal training? (Common Voice Line)
                Get down, give me 20 (Common Voice Line)
                No mercy (Common Voice Line)
                Welcome to the gun show (Common Voice Line)
                Together we are strong (Common Voice Line)
                I can bench more than you (Common Voice Line)
                Siberian bear (Common Voice Line)
                I am Mother Russia (Common Voice Line)
                In Russia, game plays you (Common Voice Line)
                I will break you (Common Voice Line)
                Taiga (Rare Skin)
                Violet (Rare Skin)
                Brick (Rare Skin)
                Goldenrod (Rare Skin)
                Dawn (Epic Skin)
                Midnight (Epic Skin)
                Industrial (Legendary Skin)
                Cybergoth (Legendary Skin)
                Siberian Front (Legendary Skin)
                Arctic (Legendary Skin)
                Icon (Common Spray)
                Shield (Common Spray)
                Surge (Common Spray)
                Pumped (Common Spray)
                512 (Common Spray)
                Barrier (Common Spray)
                Lift (Common Spray)
                Focused (Common Spray)
                Defender (Common Spray)
                Weights (Common Spray)
                For the People (Common Spray)
                Cannon (Common Spray)
                Gun Show (Common Spray)
                Pink (Common Spray)
                Champion (Common Spray)
                Wrestle (Common Spray)
                Bear (Common Spray)
                Smile (Common Spray)
                Strength (Common Spray)
                Avenger (Common Spray)
                We Are Strong (Common Spray)
                Tobelstein (Common Spray)
                Alexandra (Common Spray)
        SUMMER_GAMES_2016 (5 items)
                Weightlifting (Rare Icon)
                Weightlifting (Common Spray)
                No pain, no gain (Common Voice Line)
                Champion (Legendary Skin)
                Weightlifter (Legendary Skin)
        HALLOWEEN_2016 (3 items)
                Trick or Treat (Common Spray)
                R.I.P. (Rare Victory Pose)
                Never forget the fallen (Common Voice Line)

Cosmetics for McCree...
        ACHIEVEMENT (3 items)
                Pixel (Common Spray)
                Cute (Common Spray)
                GOLDEN (Common Weapon Skin)
        STANDARD_COMMON (7 items)
                Heroic (Common Victory Pose)
                Heroic (Common Heroic Intro)
                RANDOM (Common Heroic Intro)
                CLASSIC (Common Weapon Skin)
                Classic (Common Skin)
                Watch and learn (Common Voice Line)
                Heroic (Common Emote)
        COMMON (57 items)
                McCree (Rare Icon)
                Badge (Rare Icon)
                Deadeye (Rare Icon)
                Gunspinning (Epic Emote)
                Hat Tip (Epic Emote)
                Spit (Epic Emote)
                Joker (Epic Emote)
                Take a load off (Epic Emote)
                Take it easy (Rare Victory Pose)
                Over the Shoulder (Rare Victory Pose)
                Contemplative (Rare Victory Pose)
                The name's McCree (Epic Heroic Intro)
                The Duel (Epic Heroic Intro)
                Rolling into Action (Epic Heroic Intro)
                Ain't I killed you before (Common Voice Line)
                You done? (Common Voice Line)
                Sure as hell ain't ugly (Common Voice Line)
                I'm the quick... (Common Voice Line)
                Happens to the best of us (Common Voice Line)
                Reach for the sky (Common Voice Line)
                I tried being reasonable (Common Voice Line)
                I've got a bullet... (Common Voice Line)
                I'm your huckleberry (Common Voice Line)
                Wanted: dead or alive (Common Voice Line)
                Lake (Rare Skin)
                Sage (Rare Skin)
                Wheat (Rare Skin)
                Ebony (Rare Skin)
                On the Range (Epic Skin)
                White Hat (Epic Skin)
                Gambler (Legendary Skin)
                Riverboat (Legendary Skin)
                Mystery Man (Legendary Skin)
                Vigilante (Legendary Skin)
                Icon (Common Spray)
                Badge (Common Spray)
                Gunslinger (Common Spray)
                Tumbleweed (Common Spray)
                Bullet (Common Spray)
                Skull (Common Spray)
                Spin (Common Spray)
                Noose (Common Spray)
                Thumbs Up (Common Spray)
                Bang! (Common Spray)
                Deadeye (Common Spray)
                BAMF (Common Spray)
                Target (Common Spray)
                The Name's (Common Spray)
                Draw (Common Spray)
                Take It Easy (Common Spray)
                Jesse (Common Spray)
                Outlaw (Common Spray)
                Enigma (Common Spray)
                Wanted (Common Spray)
                High Noon (Common Spray)
                Buckle (Common Spray)
                Your Face Here (Common Spray)
        SUMMER_GAMES_2016 (4 items)
                Equestrian (Rare Icon)
                Equestrian (Common Spray)
                I don't much like losing (Common Voice Line)
                American (Epic Skin)
        HALLOWEEN_2016 (3 items)
                Trick or Treat (Common Spray)
                R.I.P. (Rare Victory Pose)
                It's your funeral (Common Voice Line)

Cosmetics for Roadhog...
        ACHIEVEMENT (3 items)
                Pixel (Common Spray)
                Cute (Common Spray)
                GOLDEN (Common Weapon Skin)
        STANDARD_COMMON (7 items)
                Heroic (Common Victory Pose)
                Heroic (Common Heroic Intro)
                RANDOM (Common Heroic Intro)
                CLASSIC (Common Weapon Skin)
                Classic (Common Skin)
                The apocalypse (Common Voice Line)
                Heroic (Common Emote)
        COMMON (57 items)
                Roadhog (Rare Icon)
                Hook (Rare Icon)
                Piggy (Rare Icon)
                Can Crusher (Epic Emote)
                Headbanging (Epic Emote)
                Boo! (Epic Emote)
                Belly Laugh (Epic Emote)
                Tuckered out (Epic Emote)
                Tuckered out (Rare Victory Pose)
                Pointing to the sky (Rare Victory Pose)
                Thumbs up (Rare Victory Pose)
                Little Piggy (Epic Heroic Intro)
                Say "Cheese" (Epic Heroic Intro)
                WHOLE HOG (Epic Heroic Intro)
                Candy from a baby (Common Voice Line)
                Piece of cake (Common Voice Line)
                Hook, line, and sinker (Common Voice Line)
                Life is pain, so is death (Common Voice Line)
                Push off (Common Voice Line)
                We're all animals (Common Voice Line)
                Violence is the answer (Common Voice Line)
                Say "bacon..." (Common Voice Line)
                Got something to say? (Common Voice Line)
                HAHAHA! (Common Voice Line)
                Kiwi (Rare Skin)
                Mud (Rare Skin)
                Sand (Rare Skin)
                Thistle (Rare Skin)
                Stitched (Epic Skin)
                Pigpen (Epic Skin)
                Toa (Legendary Skin)
                Islander (Legendary Skin)
                Mako (Legendary Skin)
                Sharkbait (Legendary Skin)
                Icon (Common Spray)
                Helmet (Common Spray)
                Fresh Meat (Common Spray)
                Wanted (Common Spray)
                No Pork (Common Spray)
                Toxic (Common Spray)
                Piggy (Common Spray)
                Mako (Common Spray)
                License (Common Spray)
                Tails (Common Spray)
                Eyes (Common Spray)
                Wild Hog (Common Spray)
                Emblem (Common Spray)
                Free Pig (Common Spray)
                Gotcha (Common Spray)
                Left (Common Spray)
                Hogpower (Common Spray)
                Popper (Common Spray)
                Here Piggy (Common Spray)
                Breathin' (Common Spray)
                Deep Thoughts (Common Spray)
                Hooked (Common Spray)
                Grand Theft (Common Spray)
        SUMMER_GAMES_2016 (4 items)
                Diving (Rare Icon)
                Diving (Common Spray)
                What's mine is mine (Common Voice Line)
                Medal (Rare Victory Pose)
        HALLOWEEN_2016 (5 items)
                Trick or Treat (Common Spray)
                R.I.P. (Rare Victory Pose)
                Junkenstein's Monster (Legendary Skin)
                The Monster (Rare Icon)
                Want some candy? (Common Voice Line)

Cosmetics for Bastion...
        ACHIEVEMENT (5 items)
                Pixel (Common Spray)
                Cute (Common Spray)
                GOLDEN (Common Weapon Skin)
                Overgrown (Legendary Skin)
                BlizzCon 2016 (Epic Skin)
        STANDARD_COMMON (7 items)
                Heroic (Common Victory Pose)
                Heroic (Common Heroic Intro)
                RANDOM (Common Heroic Intro)
                CLASSIC (Common Weapon Skin)
                Classic (Common Skin)
                Doo-woo (Common Voice Line)
                Heroic (Common Emote)
        COMMON (57 items)
                Bastion (Rare Icon)
                Tank Crossing (Rare Icon)
                Ganymede (Rare Icon)
                Dizzy (Epic Emote)
                Robot (Epic Emote)
                Alert! Alert! (Epic Emote)
                Chortle (Epic Emote)
                Rest Mode (Epic Emote)
                Birdwatching (Rare Victory Pose)
                Pop Up (Rare Victory Pose)
                Tank (Rare Victory Pose)
                On Guard (Epic Heroic Intro)
                Ganymede (Epic Heroic Intro)
                Bullet Rain (Epic Heroic Intro)
                Sh-sh-sh (Common Voice Line)
                Beeple (Common Voice Line)
                Zwee? (Common Voice Line)
                Dun dun boop boop (Common Voice Line)
                DAH-DAH WEEEEE! (Common Voice Line)
                Boo boo doo de doo (Common Voice Line)
                Hee hoo hoo (Common Voice Line)
                Bweeeeeeeeeee (Common Voice Line)
                Dweet dweet dweet! (Common Voice Line)
                Chirr chirr chirr (Common Voice Line)
                Sky (Rare Skin)
                Meadow (Rare Skin)
                Dawn (Rare Skin)
                Soot (Rare Skin)
                Omnic Crisis (Epic Skin)
                Defense Matrix (Epic Skin)
                Steambot (Legendary Skin)
                Gearbot (Legendary Skin)
                Antique (Legendary Skin)
                Woodbot (Legendary Skin)
                Icon (Common Spray)
                Fire At Will (Common Spray)
                Giant (Common Spray)
                Recovery (Common Spray)
                Ganymede (Common Spray)
                Omnic (Common Spray)
                Action (Common Spray)
                Bird (Common Spray)
                Birdwatchers (Common Spray)
                Black (Common Spray)
                Curious (Common Spray)
                e54 (Common Spray)
                Sprout (Common Spray)
                Flower Power (Common Spray)
                Wood and Stone (Common Spray)
                Flight (Common Spray)
                Blocks (Common Spray)
                Crisis (Common Spray)
                Nest (Common Spray)
                In Repair (Common Spray)
                Overgrown (Common Spray)
                Cannon (Common Spray)
                Retro (Common Spray)
        SUMMER_GAMES_2016 (4 items)
                Boxing (Rare Icon)
                Boxing (Common Spray)
                WHOO-VWEEEEEE (Common Voice Line)
                Boxing (Epic Emote)
        HALLOWEEN_2016 (4 items)
                Trick or Treat (Common Spray)
                R.I.P. (Rare Victory Pose)
                Tombstone (Epic Skin)
                W-W-Wooooo...? (Common Voice Line)

Cosmetics for Ana...
        ACHIEVEMENT (3 items)
                Pixel (Common Spray)
                Cute (Common Spray)
                GOLDEN (Common Weapon Skin)
        STANDARD_COMMON (7 items)
                Heroic (Common Victory Pose)
                Heroic (Common Heroic Intro)
                RANDOM (Common Heroic Intro)
                CLASSIC (Common Weapon Skin)
                Classic (Common Skin)
                Justice delivered (Common Voice Line)
                Heroic (Common Emote)
        COMMON (57 items)
                Ana (Rare Icon)
                Wedjat (Rare Icon)
                Watcher (Rare Icon)
                Protector (Epic Emote)
                Tea Time (Epic Emote)
                Disapproving (Epic Emote)
                Not impressed (Epic Emote)
                Take a Knee (Epic Emote)
                Protector (Rare Victory Pose)
                Seated (Rare Victory Pose)
                Mission Complete (Rare Victory Pose)
                Shh... (Epic Heroic Intro)
                Locked On (Epic Heroic Intro)
                Guardian (Epic Heroic Intro)
                Children, behave (Common Voice Line)
                What are you thinking? (Common Voice Line)
                Everyone dies (Common Voice Line)
                someone to tuck you in? (Common Voice Line)
                Mother knows best (Common Voice Line)
                No scope needed (Common Voice Line)
                Justice rains from above (Common Voice Line)
                Witness me (Common Voice Line)
                It takes a woman to know it (Common Voice Line)
                You know nothing (Common Voice Line)
                Turquoise (Rare Skin)
                Citrine (Rare Skin)
                Garnet (Rare Skin)
                Peridot (Rare Skin)
                Merciful (Epic Skin)
                Shrike (Epic Skin)
                Wasteland (Legendary Skin)
                Wadjet (Legendary Skin)
                Captain Amari (Legendary Skin)
                Horus (Legendary Skin)
                Old Soldier (Common Spray)
                Ana (Common Spray)
                Action (Common Spray)
                Wedjat (Common Spray)
                Cracked (Common Spray)
                Rifle (Common Spray)
                Wrist Launcher (Common Spray)
                Gaze (Common Spray)
                Eyepatch (Common Spray)
                Overhead (Common Spray)
                Photograph (Common Spray)
                Sidearm (Common Spray)
                Guardian (Common Spray)
                Hesitation (Common Spray)
                Shadow (Common Spray)
                Grenade (Common Spray)
                Fareeha (Common Spray)
                Zzz (Common Spray)
                Bearer (Common Spray)
                Letter (Common Spray)
                Cheer (Common Spray)
                Shhh (Common Spray)
                Icon (Common Spray)
        SUMMER_GAMES_2016 (3 items)
                Shooting (Rare Icon)
                Shooting (Common Spray)
                Learn from the Pain (Common Voice Line)
        HALLOWEEN_2016 (5 items)
                Trick or Treat (Common Spray)
                Candy (Epic Emote)
                R.I.P. (Rare Victory Pose)
                Ghoul (Epic Skin)
                Are you scared? (Common Voice Line)

Cosmetics for Zenyatta...
        ACHIEVEMENT (3 items)
                Pixel (Common Spray)
                Cute (Common Spray)
                GOLDEN (Common Weapon Skin)
        STANDARD_COMMON (7 items)
                Heroic (Common Victory Pose)
                Heroic (Common Heroic Intro)
                RANDOM (Common Heroic Intro)
                CLASSIC (Common Weapon Skin)
                Classic (Common Skin)
                We are in harmony (Common Voice Line)
                Heroic (Common Emote)
        COMMON (57 items)
                Zenyatta (Rare Icon)
                Harmony (Rare Icon)
                Meditation (Rare Icon)
                Focusing (Epic Emote)
                Round of Applause (Epic Emote)
                Taunt (Epic Emote)
                Tickled (Epic Emote)
                Meditate (Epic Emote)
                Balance (Rare Victory Pose)
                Peace (Rare Victory Pose)
                Harmony (Rare Victory Pose)
                Focused (Epic Heroic Intro)
                Harmony and Discord (Epic Heroic Intro)
                Transcendence (Epic Heroic Intro)
                Hello, world! (Common Voice Line)
                Death is whimsical today (Common Voice Line)
                Peace and blessings (Common Voice Line)
                The iris embraces you (Common Voice Line)
                Free your mind (Common Voice Line)
                I dreamt I was a butterfly (Common Voice Line)
                I will not juggle (Common Voice Line)
                Do I think? (Common Voice Line)
                Ones and zeroes (Common Voice Line)
                I think, therefore I am (Common Voice Line)
                Leaf (Rare Skin)
                Water (Rare Skin)
                Earth (Rare Skin)
                Air (Rare Skin)
                Ascendant (Epic Skin)
                Harmonious (Epic Skin)
                Ra (Legendary Skin)
                Sunyatta (Legendary Skin)
                Djinnyatta (Legendary Skin)
                Ifrit (Legendary Skin)
                Icon (Common Spray)
                Graphic (Common Spray)
                Balance (Common Spray)
                Adorable (Common Spray)
                Together (Common Spray)
                Nine (Common Spray)
                Tekhartha (Common Spray)
                Enlightened (Common Spray)
                Orbs (Common Spray)
                Flow (Common Spray)
                Throw (Common Spray)
                Guru (Common Spray)
                Hand (Common Spray)
                Peace (Common Spray)
                Taunt (Common Spray)
                Fist Bump (Common Spray)
                Discord (Common Spray)
                Harmony (Common Spray)
                Inner Fire (Common Spray)
                Contemplative (Common Spray)
                Orb (Common Spray)
                Aura (Common Spray)
                Foot (Common Spray)
        SUMMER_GAMES_2016 (4 items)
                Taekwondo (Rare Icon)
                Strive for improvement (Common Voice Line)
                Medals (Rare Victory Pose)
                Taekwondo (Common Spray)
        HALLOWEEN_2016 (4 items)
                R.I.P. (Rare Victory Pose)
                Trick or Treat (Common Spray)
                Skullyatta (Epic Skin)
                Trick or treat? (Common Voice Line)

Cosmetics for Widowmaker...
        ACHIEVEMENT (4 items)
                Pixel (Common Spray)
                Cute (Common Spray)
                GOLDEN (Common Weapon Skin)
                Noire (Legendary Skin)
        STANDARD_COMMON (7 items)
                Heroic (Common Victory Pose)
                Heroic (Common Heroic Intro)
                RANDOM (Common Heroic Intro)
                CLASSIC (Common Weapon Skin)
                Classic (Common Skin)
                A single death (Common Voice Line)
                Heroic (Common Emote)
        COMMON (57 items)
                Widowmaker (Rare Icon)
                Grappling Hook (Rare Icon)
                Baiser (Rare Icon)
                Widow's kiss (Epic Emote)
                Curtain Call (Epic Emote)
                Shot Dead (Epic Emote)
                Delighted (Epic Emote)
                At Rest (Epic Emote)
                Over the Shoulder (Rare Victory Pose)
                Activating Visor (Rare Victory Pose)
                Gaze (Rare Victory Pose)
                Swinging into Action (Epic Heroic Intro)
                I see you... (Epic Heroic Intro)
                Hanging Around (Epic Heroic Intro)
                Encore? (Common Voice Line)
                What's an aimbot? (Common Voice Line)
                Ouh là là (Common Voice Line)
                Look for the woman (Common Voice Line)
                One shot, one kill (Common Voice Line)
                Magnifique (Common Voice Line)
                Let them eat cake (Common Voice Line)
                To life, to death (Common Voice Line)
                That's how it is (Common Voice Line)
                Step into my parlor... (Common Voice Line)
                Ciel (Rare Skin)
                Vert (Rare Skin)
                Nuit (Rare Skin)
                Rose (Rare Skin)
                Winter (Epic Skin)
                Patina (Epic Skin)
                Odile (Legendary Skin)
                Odette (Legendary Skin)
                Comtesse (Legendary Skin)
                Huntress (Legendary Skin)
                Icon (Common Spray)
                Blood (Common Spray)
                Baiser (Common Spray)
                Widow's Kiss (Common Spray)
                Emblem (Common Spray)
                Crouch (Common Spray)
                Swing (Common Spray)
                Detected (Common Spray)
                Noire (Common Spray)
                Kneeling (Common Spray)
                Gaze (Common Spray)
                Veuve (Common Spray)
                Widow (Common Spray)
                Sniper (Common Spray)
                Une Balle (Common Spray)
                Black Widow (Common Spray)
                No One Escapes (Common Spray)
                Hourglass (Common Spray)
                Scope (Common Spray)
                In My Sights (Common Spray)
                Je Te Vois (Common Spray)
                Spider (Common Spray)
                Portrait (Common Spray)
        SUMMER_GAMES_2016 (5 items)
                Gymnastics (Rare Icon)
                Gymnastics (Common Spray)
                I don't miss (Common Voice Line)
                Tricolore (Epic Skin)
                Medal (Rare Victory Pose)
        HALLOWEEN_2016 (3 items)
                Trick or Treat (Common Spray)
                R.I.P. (Rare Victory Pose)
                The party is over (Common Voice Line)

Cosmetics for Reinhardt...
        ACHIEVEMENT (3 items)
                Pixel (Common Spray)
                Cute (Common Spray)
                GOLDEN (Common Weapon Skin)
        STANDARD_COMMON (7 items)
                Heroic (Common Victory Pose)
                Heroic (Common Heroic Intro)
                RANDOM (Common Heroic Intro)
                CLASSIC (Common Weapon Skin)
                Classic (Common Skin)
                I salute you (Common Voice Line)
                Heroic (Common Emote)
        COMMON (59 items)
                Reinhardt (Rare Icon)
                Scar (Rare Icon)
                Lionhardt (Rare Icon)
                Flex (Epic Emote)
                Warrior's Salute (Epic Emote)
                Taunt (Epic Emote)
                Uproarious (Epic Emote)
                Kneel (Epic Emote)
                Flex (Rare Victory Pose)
                Confident (Rare Victory Pose)
                Legendary (Rare Victory Pose)
                Hammer Down (Epic Heroic Intro)
                More stretching required (Epic Heroic Intro)
                CHARGE (Epic Heroic Intro)
                Honor and glory (Common Voice Line)
                Are you afraid? (Common Voice Line)
                Crushing machine (Common Voice Line)
                Show you how it's done (Common Voice Line)
                Crusader online (Common Voice Line)
                Bring me another (Common Voice Line)
                Respect your elders (Common Voice Line)
                This old dog (Common Voice Line)
                German engineering (Common Voice Line)
                Catch phrase! (Common Voice Line)
                Copper (Rare Skin)
                Viridian (Rare Skin)
                Brass (Rare Skin)
                Cobalt (Rare Skin)
                Paragon (Epic Skin)
                Bundeswehr (Epic Skin)
                Blackhardt (Legendary Skin)
                Bloodhardt (Legendary Skin)
                Lionhardt (Legendary Skin)
                Stonehardt (Legendary Skin)
                Balderich (Legendary Skin)
                Greifhardt (Legendary Skin)
                Icon (Common Spray)
                Emblem (Common Spray)
                Helm (Common Spray)
                Crusader (Common Spray)
                White (Common Spray)
                Hammer Down (Common Spray)
                Cracks (Common Spray)
                Charge (Common Spray)
                Fire Strike (Common Spray)
                Vigilant (Common Spray)
                Royal (Common Spray)
                Knight (Common Spray)
                Wilhelm (Common Spray)
                Roar (Common Spray)
                Glorious (Common Spray)
                Swing (Common Spray)
                Wrestle (Common Spray)
                Honor (Common Spray)
                Stein (Common Spray)
                Barrier (Common Spray)
                Earthshatter (Common Spray)
                Lion (Common Spray)
                Shield Up (Common Spray)
        SUMMER_GAMES_2016 (3 items)
                Wrestling (Rare Icon)
                Wrestling (Common Spray)
                100%% German power (Common Voice Line)
        HALLOWEEN_2016 (5 items)
                Trick or Treat (Common Spray)
                R.I.P. (Rare Victory Pose)
                Pumpkin Smash (Epic Emote)
                Coldhardt (Epic Skin)
                Smashing (Common Voice Line)

Cosmetics for Mercy...
        ACHIEVEMENT (3 items)
                Pixel (Common Spray)
                Cute (Common Spray)
                GOLDEN (Common Weapon Skin)
        STANDARD_COMMON (7 items)
                Heroic (Common Victory Pose)
                Heroic (Common Heroic Intro)
                RANDOM (Common Heroic Intro)
                CLASSIC (Common Weapon Skin)
                Classic (Common Skin)
                I have my eye on you (Common Voice Line)
                Heroic (Common Emote)
        COMMON (57 items)
                Mercy (Rare Icon)
                Guardian Angel (Rare Icon)
                Valkyrie (Rare Icon)
                Caduceus (Epic Emote)
                Applause (Epic Emote)
                No Pulse (Epic Emote)
                The Best Medicine (Epic Emote)
                Relax (Epic Emote)
                Ready for battle (Rare Victory Pose)
                Carefree (Rare Victory Pose)
                Angelic (Rare Victory Pose)
                Heroes Never Die (Epic Heroic Intro)
                Guardian Angel (Epic Heroic Intro)
                Battle Angel (Epic Heroic Intro)
                Doctor's orders (Common Voice Line)
                Take two (Common Voice Line)
                The doctor will see you (Common Voice Line)
                On a scale of 1-10 (Common Voice Line)
                Consultation fee (Common Voice Line)
                How Barbaric (Common Voice Line)
                Miracle Worker (Common Voice Line)
                Super! (Common Voice Line)
                Need a second opinion? (Common Voice Line)
                The Doctor Is In (Common Voice Line)
                Celestial (Rare Skin)
                Verdant (Rare Skin)
                Orchid (Rare Skin)
                Mist (Rare Skin)
                Cobalt (Epic Skin)
                Amber (Epic Skin)
                Devil (Legendary Skin)
                Imp (Legendary Skin)
                Valkyrie (Legendary Skin)
                Sigrún (Legendary Skin)
                Icon (Common Spray)
                Emblem (Common Spray)
                Blaster (Common Spray)
                Support (Common Spray)
                Halo (Common Spray)
                Light (Common Spray)
                Smile (Common Spray)
                On Call (Common Spray)
                Valkyrie (Common Spray)
                Swiss (Common Spray)
                Arrow (Common Spray)
                Medic (Common Spray)
                Battle Ready (Common Spray)
                Sting (Common Spray)
                Gauze (Common Spray)
                Stethoscope (Common Spray)
                Bandage (Common Spray)
                Patched Up (Common Spray)
                Ziegler (Common Spray)
                Huge Rez!! (Common Spray)
                Heroes Never Die (Common Spray)
                Resurrect (Common Spray)
                Wings (Common Spray)
        SUMMER_GAMES_2016 (4 items)
                Badminton (Rare Icon)
                Badminton (Common Spray)
                Piece of cake (Common Voice Line)
                Eidgenossin (Epic Skin)
        HALLOWEEN_2016 (5 items)
                Trick or Treat (Common Spray)
                R.I.P. (Rare Victory Pose)
                Witch (Legendary Skin)
                The Witch (Rare Icon)
                Superstition (Common Voice Line)

Cosmetics for Winston...
        ACHIEVEMENT (3 items)
                Pixel (Common Spray)
                Cute (Common Spray)
                GOLDEN (Common Weapon Skin)
        STANDARD_COMMON (7 items)
                Heroic (Common Victory Pose)
                Heroic (Common Heroic Intro)
                RANDOM (Common Heroic Intro)
                CLASSIC (Common Weapon Skin)
                Classic (Common Skin)
                Curious (Common Voice Line)
                Heroic (Common Emote)
        COMMON (57 items)
                Winston (Rare Icon)
                Peanut Butter (Rare Icon)
                Lunar Ops (Rare Icon)
                Roar (Epic Emote)
                Peanut butter? (Epic Emote)
                Monkey Business (Epic Emote)
                Laughing Matter (Epic Emote)
                Sitting Around (Epic Emote)
                The Thinker (Rare Victory Pose)
                Glasses (Rare Victory Pose)
                Beast (Rare Victory Pose)
                Primal Rage (Epic Heroic Intro)
                Glasses (Epic Heroic Intro)
                Excuse Me (Epic Heroic Intro)
                No monkey business (Common Voice Line)
                Natural selection (Common Voice Line)
                Don't get me angry (Common Voice Line)
                How embarrassing! (Common Voice Line)
                The power of science! (Common Voice Line)
                ...Excuse me (Common Voice Line)
                Peanut butter? (Common Voice Line)
                Sorry about that! (Common Voice Line)
                We have a problem (Common Voice Line)
                I do not want a banana (Common Voice Line)
                Forest (Rare Skin)
                Atmosphere (Rare Skin)
                Banana (Rare Skin)
                Red Planet (Rare Skin)
                Desert (Epic Skin)
                Horizon (Epic Skin)
                Undersea (Legendary Skin)
                Frogston (Legendary Skin)
                Explorer (Legendary Skin)
                Safari (Legendary Skin)
                Icon (Common Spray)
                Lexigrams (Common Spray)
                Science! (Common Spray)
                Horizon (Common Spray)
                PB (Common Spray)
                White (Common Spray)
                Ape Crossing (Common Spray)
                Q.E.D. (Common Spray)
                Serious (Common Spray)
                Mine! (Common Spray)
                Lightning (Common Spray)
                Explorer (Common Spray)
                Wow (Common Spray)
                Research (Common Spray)
                Harold (Common Spray)
                Swing (Common Spray)
                Banana (Common Spray)
                Baby (Common Spray)
                Primal Rage (Common Spray)
                Angry (Common Spray)
                Roar (Common Spray)
                Rage (Common Spray)
                Fastball (Common Spray)
        SUMMER_GAMES_2016 (4 items)
                Volleyball (Rare Icon)
                Volleyball (Common Spray)
                Playtime's over (Common Voice Line)
                Medal (Rare Victory Pose)
        HALLOWEEN_2016 (4 items)
                Trick or Treat (Common Spray)
                Shadow Puppets (Epic Emote)
                R.I.P. (Rare Victory Pose)
                This is not a costume (Common Voice Line)

Cosmetics for Genji...
        ACHIEVEMENT (5 items)
                Pixel (Common Spray)
                Cute (Common Spray)
                Oni (Common Spray)
                Oni (Legendary Skin)
                GOLDEN (Common Weapon Skin)
        STANDARD_COMMON (7 items)
                Heroic (Common Victory Pose)
                Heroic (Common Heroic Intro)
                RANDOM (Common Heroic Intro)
                CLASSIC (Common Weapon Skin)
                Classic (Common Skin)
                A steady blade (Common Voice Line)
                Heroic (Common Emote)
        COMMON (57 items)
                Genji (Rare Icon)
                Nin (Rare Icon)
                God of War (Rare Icon)
                Cutting Edge (Epic Emote)
                Salute (Epic Emote)
                Challenge (Epic Emote)
                Amusing (Epic Emote)
                Meditate (Epic Emote)
                Shuriken (Rare Victory Pose)
                Kneeling (Rare Victory Pose)
                Sword stance (Rare Victory Pose)
                Unsheathing the Sword (Epic Heroic Intro)
                Warrior's Salute (Epic Heroic Intro)
                Shuriken (Epic Heroic Intro)
                Come on! (Common Voice Line)
                I am prepared! (Common Voice Line)
                My soul seeks balance (Common Voice Line)
                Let's fight! (Common Voice Line)
                Yeah! (Common Voice Line)
                Measure twice, cut once (Common Voice Line)
                You are only human (Common Voice Line)
                Damn! (Common Voice Line)
                Simple (Common Voice Line)
                Not good enough (Common Voice Line)
                Azurite (Rare Skin)
                Malachite (Rare Skin)
                Ochre (Rare Skin)
                Cinnabar (Rare Skin)
                Carbon Fiber (Epic Skin)
                Chrome (Epic Skin)
                Young Genji (Legendary Skin)
                Sparrow (Legendary Skin)
                Bedouin (Legendary Skin)
                Nomad (Legendary Skin)
                Icon (Common Spray)
                Nin (Common Spray)
                God of War (Common Spray)
                Signature (Common Spray)
                Ryugekiken (Common Spray)
                Kaze no Gotoku (Common Spray)
                Lunge (Common Spray)
                Green Ninja (Common Spray)
                Dragonblade (Common Spray)
                Shuriken (Common Spray)
                Dragon (Common Spray)
                Warrior (Common Spray)
                Stoic (Common Spray)
                Assassin (Common Spray)
                Swords (Common Spray)
                Draw (Common Spray)
                Shimada (Common Spray)
                Stance (Common Spray)
                Soul (Common Spray)
                Fully Loaded (Common Spray)
                Onmyodo (Common Spray)
                Prepared (Common Spray)
                Target Practice (Common Spray)
        SUMMER_GAMES_2016 (4 items)
                Fencing (Rare Icon)
                Fencing (Common Spray)
                I was hoping for a challenge (Common Voice Line)
                Nihon (Epic Skin)
        HALLOWEEN_2016 (4 items)
                Trick or Treat (Common Spray)
                Pumpkin Carving (Epic Heroic Intro)
                R.I.P. (Rare Victory Pose)
                My Halloween costume? (Common Voice Line)

Cosmetics for Symmetra...
        ACHIEVEMENT (3 items)
                Pixel (Common Spray)
                Cute (Common Spray)
                GOLDEN (Common Weapon Skin)
        STANDARD_COMMON (7 items)
                Heroic (Common Victory Pose)
                Heroic (Common Heroic Intro)
                RANDOM (Common Heroic Intro)
                CLASSIC (Common Weapon Skin)
                Classic (Common Skin)
                Such a lack of imagination (Common Voice Line)
                Heroic (Common Emote)
        COMMON (57 items)
                Symmetra (Rare Icon)
                Vishkar (Rare Icon)
                Sentry (Rare Icon)
                Flow (Epic Emote)
                Clap (Epic Emote)
                Insignificant (Epic Emote)
                Snicker (Epic Emote)
                Have a Seat (Epic Emote)
                Creation (Rare Victory Pose)
                Balance (Rare Victory Pose)
                Dance (Rare Victory Pose)
                Dance (Epic Heroic Intro)
                My reality (Epic Heroic Intro)
                Askew (Epic Heroic Intro)
                Why do you struggle? (Common Voice Line)
                Perfect harmony (Common Voice Line)
                How unsightly (Common Voice Line)
                Exquisite (Common Voice Line)
                Put you in your place (Common Voice Line)
                Precisely (Common Voice Line)
                Welcome to my reality (Common Voice Line)
                Everything by design (Common Voice Line)
                Impressive (Common Voice Line)
                I don't think so (Common Voice Line)
                Hyacinth (Rare Skin)
                Cardamom (Rare Skin)
                Saffron (Rare Skin)
                Technomancer (Rare Skin)
                Regal (Epic Skin)
                Utopaea (Epic Skin)
                Devi (Legendary Skin)
                Goddess (Legendary Skin)
                Vishkar (Legendary Skin)
                Architech (Legendary Skin)
                Icon (Common Spray)
                Vishkar (Common Spray)
                Light (Common Spray)
                Visor (Common Spray)
                Lotus (Common Spray)
                Projector (Common Spray)
                Behold (Common Spray)
                Pose (Common Spray)
                Glove (Common Spray)
                Vaswani (Common Spray)
                Builder (Common Spray)
                Architect (Common Spray)
                Superior (Common Spray)
                Weaver (Common Spray)
                Design (Common Spray)
                Agent (Common Spray)
                Will (Common Spray)
                Car Wash (Common Spray)
                Lines (Common Spray)
                Blueprint (Common Spray)
                Caution (Common Spray)
                The Path (Common Spray)
                Satya (Common Spray)
        SUMMER_GAMES_2016 (4 items)
                Rhythmic Gymnastics (Rare Icon)
                Rhythmic (Common Spray)
                Hard work and dedication (Common Voice Line)
                Ribbon (Epic Emote)
        HALLOWEEN_2016 (4 items)
                Trick or Treat (Common Spray)
                Vampire (Epic Skin)
                R.I.P. (Rare Victory Pose)
                A frightening thought (Common Voice Line)

Cosmetics for Mei...
        ACHIEVEMENT (3 items)
                Pixel (Common Spray)
                Cute (Common Spray)
                GOLDEN (Common Weapon Skin)
        STANDARD_COMMON (7 items)
                Heroic (Common Victory Pose)
                Heroic (Common Heroic Intro)
                RANDOM (Common Heroic Intro)
                CLASSIC (Common Weapon Skin)
                Classic (Common Skin)
                Hang in there (Common Voice Line)
                Heroic (Common Emote)
        COMMON (57 items)
                Mei (Rare Icon)
                Snowball (Rare Icon)
                Hairpin (Rare Icon)
                Companion (Epic Emote)
                Yaaaaaaaaay! (Epic Emote)
                Spray (Epic Emote)
                Giggle (Epic Emote)
                Kneel (Epic Emote)
                Hands on Hips (Rare Victory Pose)
                Casual (Rare Victory Pose)
                Kneeling (Rare Victory Pose)
                Going Up! (Epic Heroic Intro)
                Frosty :) (Epic Heroic Intro)
                Skating Around (Epic Heroic Intro)
                Okay! (Common Voice Line)
                Yay! (Common Voice Line)
                Fight for our world (Common Voice Line)
                Ouch, are you okay? (Common Voice Line)
                That was great (Common Voice Line)
                Learned your lesson (Common Voice Line)
                Sorry sorry sorry sorry (Common Voice Line)
                You have to let it go (Common Voice Line)
                Chill out! (Common Voice Line)
                A-Mei-zing! (Common Voice Line)
                Chrysanthemum (Rare Skin)
                Persimmon (Rare Skin)
                Heliotrope (Rare Skin)
                Jade (Rare Skin)
                Earthen (Epic Skin)
                Snow Plum (Epic Skin)
                Rescue Mei (Legendary Skin)
                Firefighter (Legendary Skin)
                Yeti Hunter (Legendary Skin)
                Abominable (Legendary Skin)
                Icon (Common Spray)
                Blaster (Common Spray)
                Snowman (Common Spray)
                Eyes (Common Spray)
                Walled (Common Spray)
                Reading (Common Spray)
                Mei's Journal (Common Spray)
                Smile (Common Spray)
                Dizzy (Common Spray)
                Sketch (Common Spray)
                Explorer (Common Spray)
                Popsicle (Common Spray)
                Hairpin (Common Spray)
                Print (Common Spray)
                Snow Art (Common Spray)
                ^_^ (Common Spray)
                >_\< (Common Spray)
                Confident (Common Spray)
                Casual (Common Spray)
                Snowball (Common Spray)
                Beat the Heat (Common Spray)
                Carefree (Common Spray)
                Soft Serve (Common Spray)
        SUMMER_GAMES_2016 (4 items)
                Table Tennis (Rare Icon)
                Table Tennis (Common Spray)
                Overcome all obstacles (Common Voice Line)
                Medal (Rare Victory Pose)
        HALLOWEEN_2016 (4 items)
                Trick or Treat (Common Spray)
                R.I.P. (Rare Victory Pose)
                Ice Scream (Epic Heroic Intro)
                Scary! (Common Voice Line)

Cosmetics for Sombra...
        ACHIEVEMENT (3 items)
                Pixel (Common Spray)
                Cute (Common Spray)
                GOLDEN (Common Weapon Skin)
        STANDARD_COMMON (7 items)
                Heroic (Common Victory Pose)
                Heroic (Common Heroic Intro)
                RANDOM (Common Heroic Intro)
                CLASSIC (Common Weapon Skin)
                Classic (Common Skin)
                Playing Fair (Common Voice Line)
                Heroic (Common Emote)
        COMMON (58 items)
                Sombra (Rare Icon)
                Skull (Rare Icon)
                Hacker (Rare Icon)
                Amused (Epic Emote)
                Masterpiece (Epic Emote)
                Hold On (Epic Emote)
                Kneeling (Rare Victory Pose)
                Rising (Rare Victory Pose)
                Hacked (Rare Victory Pose)
                Undetected (Epic Heroic Intro)
                Hacking (Epic Heroic Intro)
                Pulse (Epic Heroic Intro)
                Hack the Planet (Common Voice Line)
                Mess with the best... (Common Voice Line)
                Glitch in the system (Common Voice Line)
                In over your head (Common Voice Line)
                Did you mean to do that? (Common Voice Line)
                Taking this very seriously (Common Voice Line)
                Show me what you got (Common Voice Line)
                Good one (Common Voice Line)
                Cool (Common Voice Line)
                Just squishing a bug (Common Voice Line)
                Cidro (Rare Skin)
                Incendio (Rare Skin)
                Mar (Rare Skin)
                Noche (Rare Skin)
                Glitch (Epic Skin)
                Virus (Epic Skin)
                Los Muertos (Legendary Skin)
                Azúcar (Legendary Skin)
                Cyberspace (Legendary Skin)
                Augmented (Legendary Skin)
                Marionette (Common Spray)
                Calavera (Common Spray)
                Neural (Common Spray)
                Hacked (Common Spray)
                Virus (Common Spray)
                Illusive (Common Spray)
                Machine Pistol (Common Spray)
                Unlocked (Common Spray)
                ¿Quién? (Common Spray)
                Translocator (Common Spray)
                Superior (Common Spray)
                Power (Common Spray)
                5kull (Common Spray)
                Tagged (Common Spray)
                Eyes (Common Spray)
                Skycode (Common Spray)
                Web (Common Spray)
                Skull (Common Spray)
                Key (Common Spray)
                Hacked the Moon (Common Spray)
                Agent (Common Spray)
                Hacker (Common Spray)
                Deaf-Mute (Common Spray)
                Puzzle (Common Spray)
                Behind You (Common Spray)
                Icon (Common Spray)

Cosmetics for Pharah...
        ACHIEVEMENT (4 items)
                Pixel (Common Spray)
                Cute (Common Spray)
                GOLDEN (Common Weapon Skin)
                Security Chief (Legendary Skin)
        STANDARD_COMMON (7 items)
                Heroic (Common Victory Pose)
                Heroic (Common Heroic Intro)
                RANDOM (Common Heroic Intro)
                CLASSIC (Common Weapon Skin)
                Classic (Common Skin)
                Security in my hands (Common Voice Line)
                Heroic (Common Emote)
        COMMON (57 items)
                Pharah (Rare Icon)
                Raptora (Rare Icon)
                Wadjet (Rare Icon)
                Flourish (Epic Emote)
                Cheer (Epic Emote)
                Knuckles (Epic Emote)
                Chuckle (Epic Emote)
                Take a knee (Epic Emote)
                Jump Jet (Rare Victory Pose)
                Guardian (Rare Victory Pose)
                Kneeling (Rare Victory Pose)
                Touchdown (Epic Heroic Intro)
                Mission Complete (Epic Heroic Intro)
                Barrage (Epic Heroic Intro)
                Got you on my radar (Common Voice Line)
                Leave this to a professional (Common Voice Line)
                Shot down (Common Voice Line)
                Flying the friendly skies (Common Voice Line)
                Not a chance (Common Voice Line)
                Aerial superiority achieved (Common Voice Line)
                Rocket jump? (Common Voice Line)
                Sorry, but I need to jet (Common Voice Line)
                Play nice, play Pharah (Common Voice Line)
                Fly like an egyptian (Common Voice Line)
                Emerald (Rare Skin)
                Amethyst (Rare Skin)
                Titanium (Rare Skin)
                Copper (Rare Skin)
                Anubis (Epic Skin)
                Jackal (Epic Skin)
                Mechaqueen (Legendary Skin)
                Raptorion (Legendary Skin)
                Thunderbird (Legendary Skin)
                Raindancer (Legendary Skin)
                Raptora (Common Spray)
                Wedjat (Common Spray)
                Statue (Common Spray)
                Rocket Jump (Common Spray)
                Icon (Common Spray)
                Hieroglyph (Common Spray)
                Justice... (Common Spray)
                Guardian (Common Spray)
                Wings (Common Spray)
                Stone (Common Spray)
                Rocket Launcher (Common Spray)
                Tattoo (Common Spray)
                Ana (Common Spray)
                Incoming (Common Spray)
                Wrist Launcher (Common Spray)
                Cobra (Common Spray)
                Scarab (Common Spray)
                Amari (Common Spray)
                On Guard (Common Spray)
                Salute (Common Spray)
                Play Pharah (Common Spray)
                Aerial Superiority (Common Spray)
                Concussive Blast (Common Spray)
        SUMMER_GAMES_2016 (4 items)
                Basketball (Rare Icon)
                Basketball (Common Spray)
                We are in this together (Common Voice Line)
                Medal (Rare Victory Pose)
        HALLOWEEN_2016 (4 items)
                Trick or Treat (Common Spray)
                R.I.P. (Rare Victory Pose)
                Possessed (Epic Skin)
                Dead or alive (Common Voice Line)

Cosmetics for Hanzo...
        ACHIEVEMENT (3 items)
                Pixel (Common Spray)
                Cute (Common Spray)
                GOLDEN (Common Weapon Skin)
        STANDARD_COMMON (7 items)
                Heroic (Common Victory Pose)
                Heroic (Common Heroic Intro)
                RANDOM (Common Heroic Intro)
                CLASSIC (Common Weapon Skin)
                Classic (Common Skin)
                Expect nothing less (Common Voice Line)
                Heroic (Common Emote)
        COMMON (57 items)
                Hanzo (Rare Icon)
                Storm (Rare Icon)
                Shimada (Rare Icon)
                Brush shoulder (Epic Emote)
                Victory (Epic Emote)
                Beckon (Epic Emote)
                Chuckle (Epic Emote)
                Meditate (Epic Emote)
                Confident (Rare Victory Pose)
                Over the Shoulder (Rare Victory Pose)
                Kneeling (Rare Victory Pose)
                My Aim Is True (Epic Heroic Intro)
                Superior (Epic Heroic Intro)
                Backflip (Epic Heroic Intro)
                Remember this moment (Common Voice Line)
                Flow like water (Common Voice Line)
                Hm... (Common Voice Line)
                I do what I must (Common Voice Line)
                Never second best (Common Voice Line)
                From one thing... (Common Voice Line)
                Sake! (Common Voice Line)
                Never in doubt (Common Voice Line)
                Spirit dragon (Common Voice Line)
                Step into the dojo (Common Voice Line)
                Azuki (Rare Skin)
                Midori (Rare Skin)
                Kinoko (Rare Skin)
                Sora (Rare Skin)
                Cloud (Epic Skin)
                Dragon (Epic Skin)
                Young Hanzo (Legendary Skin)
                Young Master (Legendary Skin)
                Okami (Legendary Skin)
                Lone Wolf (Legendary Skin)
                Icon (Common Spray)
                Seal (Common Spray)
                Nin (Common Spray)
                Haori (Common Spray)
                Duty (Common Spray)
                Wanderer (Common Spray)
                Yellow (Common Spray)
                Spray (Common Spray)
                Kumo (Common Spray)
                Archer (Common Spray)
                Dragonstrike (Common Spray)
                Successor (Common Spray)
                Challenge (Common Spray)
                Cloud (Common Spray)
                Kneeling (Common Spray)
                Dragons (Common Spray)
                Scarf (Common Spray)
                Stoic (Common Spray)
                Moon (Common Spray)
                Dragon (Common Spray)
                Sake (Common Spray)
                Tea (Common Spray)
                Drawn (Common Spray)
        SUMMER_GAMES_2016 (3 items)
                Archery (Rare Icon)
                Archery (Common Spray)
                Ignore all distractions (Common Voice Line)
        HALLOWEEN_2016 (4 items)
                Trick or Treat (Common Spray)
                R.I.P. (Rare Victory Pose)
                Demon (Epic Skin)
                You are already dead (Common Voice Line)

Cosmetics for Torbjörn...
        ACHIEVEMENT (3 items)
                Pixel (Common Spray)
                Cute (Common Spray)
                GOLDEN (Common Weapon Skin)
        STANDARD_COMMON (7 items)
                Heroic (Common Victory Pose)
                Heroic (Common Heroic Intro)
                RANDOM (Common Heroic Intro)
                CLASSIC (Common Weapon Skin)
                Classic (Common Skin)
                Hard work pays off (Common Voice Line)
                Heroic (Common Emote)
        COMMON (57 items)
                Torbjörn (Rare Icon)
                Forge (Rare Icon)
                Gears (Rare Icon)
                Overload (Epic Emote)
                Clicking heels (Epic Emote)
                Fisticuffs (Epic Emote)
                Guffaw (Epic Emote)
                Taking a Break (Epic Emote)
                Hammer (Rare Victory Pose)
                Sitting Pretty (Rare Victory Pose)
                Take five (Rare Victory Pose)
                Ride 'Em (Epic Heroic Intro)
                Refreshing (Epic Heroic Intro)
                In your face (Epic Heroic Intro)
                Leave this to an expert (Common Voice Line)
                Working as intended (Common Voice Line)
                A chicken out of a feather (Common Voice Line)
                I'm Swedish! (Common Voice Line)
                Engineers (Common Voice Line)
                Let's not buy the pig (Common Voice Line)
                Don't get caught (Common Voice Line)
                Some assembly required (Common Voice Line)
                I'm giving it all I've got! (Common Voice Line)
                Completion date? (Common Voice Line)
                Citron (Rare Skin)
                Grön (Rare Skin)
                Blå (Rare Skin)
                Plommon (Rare Skin)
                Woodclad (Epic Skin)
                Cathode (Epic Skin)
                Deadlock (Legendary Skin)
                Chopper (Legendary Skin)
                Blackbeard (Legendary Skin)
                Barbarossa (Legendary Skin)
                Icon (Common Spray)
                Gears (Common Spray)
                Uppgradera (Common Spray)
                Smält (Common Spray)
                Fix It Up (Common Spray)
                Kanon (Common Spray)
                Forged (Common Spray)
                Armor (Common Spray)
                Stoic (Common Spray)
                Ironclad (Common Spray)
                Turret (Common Spray)
                Hot (Common Spray)
                Hammer (Common Spray)
                Claw (Common Spray)
                Mask (Common Spray)
                Beard (Common Spray)
                Ready to Work (Common Spray)
                Catch a Ride (Common Spray)
                Run! (Common Spray)
                Chef (Common Spray)
                Molten Core (Common Spray)
                Turrets (Common Spray)
                Get Ready (Common Spray)
        SUMMER_GAMES_2016 (5 items)
                Water Polo (Rare Icon)
                Water Polo (Common Spray)
                More where that came from (Common Voice Line)
                Tre Kronor (Epic Skin)
                Medal (Rare Victory Pose)
        HALLOWEEN_2016 (3 items)
                Trick or Treat (Common Spray)
                R.I.P. (Rare Victory Pose)
                If you build it (Common Voice Line)

Cosmetics for Junkrat...
        ACHIEVEMENT (3 items)
                Pixel (Common Spray)
                Cute (Common Spray)
                GOLDEN (Common Weapon Skin)
        STANDARD_COMMON (7 items)
                Heroic (Common Victory Pose)
                Heroic (Common Heroic Intro)
                RANDOM (Common Heroic Intro)
                CLASSIC (Common Weapon Skin)
                Classic (Common Skin)
                Tick-tock-tick-tock (Common Voice Line)
                Heroic (Common Emote)
        COMMON (57 items)
                Junkrat (Rare Icon)
                Have a Nice Day! (Rare Icon)
                AHHHH! (Rare Icon)
                Juggling (Epic Emote)
                Vaudeville (Epic Emote)
                Puppet (Epic Emote)
                Can't deal (Epic Emote)
                Lounging (Epic Emote)
                It'll Freeze That Way (Rare Victory Pose)
                Kneeling (Rare Victory Pose)
                Nyah nyah (Rare Victory Pose)
                RIP-Tire (Epic Heroic Intro)
                Unfortunate (Epic Heroic Intro)
                I'm Flying! (Epic Heroic Intro)
                Anyone want some bbq? (Common Voice Line)
                Brrring! (Common Voice Line)
                Coming up explodey! (Common Voice Line)
                Happy birthday (Common Voice Line)
                Kaboom (Common Voice Line)
                Smile! (Common Voice Line)
                Have a nice day! (Common Voice Line)
                It's the little things (Common Voice Line)
                ...blow it up again (Common Voice Line)
                Ooh, shiny (Common Voice Line)
                Bleached (Rare Skin)
                Irradiated (Rare Skin)
                Rusted (Rare Skin)
                Drowned (Rare Skin)
                Jailbird (Epic Skin)
                Toasted (Epic Skin)
                Jester (Legendary Skin)
                Fool (Legendary Skin)
                Scarecrow (Legendary Skin)
                Hayseed (Legendary Skin)
                Icon (Common Spray)
                Smile (Common Spray)
                Kaboom! (Common Spray)
                Frag (Common Spray)
                Wanted (Common Spray)
                Bang Bang (Common Spray)
                Spin (Common Spray)
                Mad (Common Spray)
                Fuse (Common Spray)
                Trapper (Common Spray)
                Crazy (Common Spray)
                Grin (Common Spray)
                Minefield (Common Spray)
                Rolling (Common Spray)
                Firework (Common Spray)
                Mine (Common Spray)
                Smoke (Common Spray)
                Vroom!! (Common Spray)
                For You (Common Spray)
                Mayhem (Common Spray)
                AHHHH! (Common Spray)
                Fireball (Common Spray)
                Junk (Common Spray)
        SUMMER_GAMES_2016 (4 items)
                Tennis (Rare Icon)
                Tennis (Common Spray)
                I give it a 10! (Common Voice Line)
                Shot Put (Epic Heroic Intro)
        HALLOWEEN_2016 (5 items)
                Trick or Treat (Common Spray)
                R.I.P. (Rare Victory Pose)
                Dr. Junkenstein (Legendary Skin)
                The Doctor (Rare Icon)
                Happy Halloween (Common Voice Line)

Cosmetics for Tracer...
        ACHIEVEMENT (4 items)
                Pixel (Common Spray)
                Cute (Common Spray)
                GOLDEN (Common Weapon Skin)
                Slipstream (Legendary Skin)
        STANDARD_COMMON (7 items)
                Heroic (Common Victory Pose)
                Heroic (Common Heroic Intro)
                RANDOM (Common Heroic Intro)
                CLASSIC (Common Weapon Skin)
                Classic (Common Skin)
                You got it (Common Voice Line)
                Heroic (Common Emote)
        COMMON (56 items)
                Tracer (Rare Icon)
                Pulse Bomb (Rare Icon)
                Patch (Rare Icon)
                Spin (Epic Emote)
                Cheer (Epic Emote)
                Having a laugh (Epic Emote)
                Sitting Around... (Epic Emote)
                Salute (Rare Victory Pose)
                Over the Shoulder (Rare Victory Pose)
                Sitting (Rare Victory Pose)
                Just in Time (Epic Heroic Intro)
                Serious Business (Epic Heroic Intro)
                Backflip (Epic Heroic Intro)
                Aw, rubbish (Common Voice Line)
                Under control (Common Voice Line)
                The world needs heroes (Common Voice Line)
                You need a time out (Common Voice Line)
                Check me out (Common Voice Line)
                She shoots, she scores (Common Voice Line)
                Cheers, love! (Common Voice Line)
                Keep calm (Common Voice Line)
                Be right back! (Common Voice Line)
                déjà vu (Common Voice Line)
                Neon Green (Rare Skin)
                Royal Blue (Rare Skin)
                Hot Pink (Rare Skin)
                Electric Purple (Rare Skin)
                Posh (Epic Skin)
                Sporty (Epic Skin)
                Punk (Legendary Skin)
                Ultraviolet (Legendary Skin)
                T. Racer (Legendary Skin)
                Mach T (Legendary Skin)
                Icon (Common Spray)
                Wings (Common Spray)
                Blink (Common Spray)
                Fighter (Common Spray)
                Cheers, Love (Common Spray)
                Tagged (Common Spray)
                Orange (Common Spray)
                Lena (Common Spray)
                Clock's Tickin' (Common Spray)
                Pistols (Common Spray)
                Shaded (Common Spray)
                Pulse Bomb (Common Spray)
                Bomb's Away! (Common Spray)
                Ready for Action (Common Spray)
                Confident (Common Spray)
                Kneeling (Common Spray)
                Whatcha' Lookin' At? (Common Spray)
                Cavalry's Here (Common Spray)
                Cheers (Common Spray)
                Pew! Pew! Pew! (Common Spray)
                Poster (Common Spray)
                Salute (Common Spray)
                Portrait (Common Spray)
        SUMMER_GAMES_2016 (6 items)
                Track (Rare Icon)
                Track (Common Spray)
                Eat my dust (Common Voice Line)
                Hurdle (Epic Heroic Intro)
                Sprinter (Legendary Skin)
                Track and Field (Legendary Skin)
        HALLOWEEN_2016 (3 items)
                Trick or Treat (Common Spray)
                R.I.P. (Rare Victory Pose)
                Ooh, Scary! (Common Voice Line)

Cosmetics for D.Va...
        ACHIEVEMENT (3 items)
                Pixel (Common Spray)
                Cute (Common Spray)
                GOLDEN (Common Weapon Skin)
        STANDARD_COMMON (7 items)
                Heroic (Common Victory Pose)
                Heroic (Common Heroic Intro)
                RANDOM (Common Heroic Intro)
                CLASSIC (Common Weapon Skin)
                Classic (Common Skin)
                Love, D.Va (Common Voice Line)
                Heroic (Common Emote)
        COMMON (57 items)
                D.Va (Rare Icon)
                Bunny (Rare Icon)
                Charm (Rare Icon)
                heartbreaker (Epic Emote)
                Party Time (Epic Emote)
                Bunny Hop (Epic Emote)
                ^o^ (Epic Emote)
                Game On (Legendary Emote)
                I heart you (Rare Victory Pose)
                Peace (Rare Victory Pose)
                Sitting (Rare Victory Pose)
                Eject (Epic Heroic Intro)
                Lying Around (Epic Heroic Intro)
                MEKA Activated (Epic Heroic Intro)
                LOL (Common Voice Line)
                No hacks required (Common Voice Line)
                I play to win (Common Voice Line)
                Aw, yeah! (Common Voice Line)
                AFK (Common Voice Line)
                D.Va: 1, bad guys: 0 (Common Voice Line)
                ;) (Common Voice Line)
                gg! (Common Voice Line)
                Is this easy mode? (Common Voice Line)
                A new challenger! (Common Voice Line)
                Blueberry (Rare Skin)
                Lemon-Lime (Rare Skin)
                Tangerine (Rare Skin)
                Watermelon (Rare Skin)
                Carbon Fiber (Epic Skin)
                White Rabbit (Epic Skin)
                B.Va (Legendary Skin)
                Junebug (Legendary Skin)
                Junker (Legendary Skin)
                Scavenger (Legendary Skin)
                Icon (Common Spray)
                B.Ny (Common Spray)
                Diva (Common Spray)
                Light Gun (Common Spray)
                Hana (Common Spray)
                Unload (Common Spray)
                Bunny Hop (Common Spray)
                Love D.Va (Common Spray)
                Salt (Common Spray)
                Walk of Fame (Common Spray)
                Star (Common Spray)
                Watching (Common Spray)
                Bubble (Common Spray)
                Pixel Bunny (Common Spray)
                Headset (Common Spray)
                Bubble Gum (Common Spray)
                Photo (Common Spray)
                Bang (Common Spray)
                Nano Cola (Common Spray)
                MEKA (Common Spray)
                Power Up! (Common Spray)
                GG (Common Spray)
                Heart (Common Spray)
        SUMMER_GAMES_2016 (4 items)
                Cycling (Rare Icon)
                Cycling (Common Spray)
                I'm #1 (Common Voice Line)
                Taegeukgi (Epic Skin)
        HALLOWEEN_2016 (3 items)
                Trick or Treat (Common Spray)
                R.I.P. (Rare Victory Pose)
                Happy Halloween! (Common Voice Line)

Cosmetics for Soldier: 76...
        ACHIEVEMENT (4 items)
                Pixel (Common Spray)
                Cute (Common Spray)
                GOLDEN (Common Weapon Skin)
                Strike-Commander Morrison (Legendary Skin)
        STANDARD_COMMON (7 items)
                Heroic (Common Victory Pose)
                Heroic (Common Heroic Intro)
                RANDOM (Common Heroic Intro)
                CLASSIC (Common Weapon Skin)
                Classic (Common Skin)
                I've still got it (Common Voice Line)
                Heroic (Common Emote)
        COMMON (57 items)
                Soldier: 76 (Rare Icon)
                Strike-Commander (Rare Icon)
                76 (Rare Icon)
                Locked and Loaded (Epic Emote)
                Fist (Epic Emote)
                I see you (Epic Emote)
                Amused (Epic Emote)
                Take a Knee (Epic Emote)
                Soldier (Rare Victory Pose)
                Locked and Loaded (Rare Victory Pose)
                Fist Pump (Rare Victory Pose)
                Looking at You (Epic Heroic Intro)
                Target Rich Environment (Epic Heroic Intro)
                HELIX (Epic Heroic Intro)
                You didn't make the cut (Common Voice Line)
                Not on my watch (Common Voice Line)
                That's "sir" to you (Common Voice Line)
                I didn't start this war... (Common Voice Line)
                Old soldiers (Common Voice Line)
                What are you lookin' at? (Common Voice Line)
                I'm an army of one (Common Voice Line)
                You're the other one (Common Voice Line)
                Smells like victory (Common Voice Line)
                Get off my lawn (Common Voice Line)
                Olive (Rare Skin)
                Russet (Rare Skin)
                Smoke (Rare Skin)
                Jet (Rare Skin)
                Bone (Epic Skin)
                Golden (Epic Skin)
                Daredevil: 76 (Legendary Skin)
                Stunt Rider: 76 (Legendary Skin)
                Commando: 76 (Legendary Skin)
                Night Ops: 76 (Legendary Skin)
                Icon (Common Spray)
                Helix (Common Spray)
                Heal Up (Common Spray)
                Jacket: 76 (Common Spray)
                Grave (Common Spray)
                Wanted (Common Spray)
                Move! (Common Spray)
                Coin (Common Spray)
                Visor (Common Spray)
                Vigilante (Common Spray)
                Hooah (Common Spray)
                76 (Common Spray)
                Pulse Rifle (Common Spray)
                Strike Commander (Common Spray)
                Rockets (Common Spray)
                Grizzled (Common Spray)
                Muzzle (Common Spray)
                Rifle: 76 (Common Spray)
                Resolute (Common Spray)
                All Soldiers (Common Spray)
                Old Soldier (Common Spray)
                Salute (Common Spray)
                American Hero (Common Spray)
        SUMMER_GAMES_2016 (4 items)
                Golf (Rare Icon)
                Golf (Common Spray)
                You want a medal? (Common Voice Line)
                Golf Swing (Rare Victory Pose)
        HALLOWEEN_2016 (4 items)
                Trick or Treat (Common Spray)
                R.I.P. (Rare Victory Pose)
                Immortal (Epic Skin)
                Knock knock (Common Voice Line)

Cosmetics for Lúcio...
        ACHIEVEMENT (3 items)
                Pixel (Common Spray)
                Cute (Common Spray)
                GOLDEN (Common Weapon Skin)
        STANDARD_COMMON (7 items)
                Heroic (Common Victory Pose)
                Heroic (Common Heroic Intro)
                RANDOM (Common Heroic Intro)
                CLASSIC (Common Weapon Skin)
                Classic (Common Skin)
                To the rhythm (Common Voice Line)
                Heroic (Common Emote)
        COMMON (57 items)
                Lúcio (Rare Icon)
                Kambô (Rare Icon)
                Frog (Rare Icon)
                In the Groove (Epic Emote)
                Capoeira (Epic Emote)
                Nah! (Epic Emote)
                Knee Slapper (Epic Emote)
                Chilling (Epic Emote)
                Ready for Action (Rare Victory Pose)
                Grooving (Rare Victory Pose)
                Confident (Rare Victory Pose)
                Drop the beat (Epic Heroic Intro)
                In the Groove (Epic Heroic Intro)
                Freestyle (Epic Heroic Intro)
                Oh, yeah! (Common Voice Line)
                Why are you so angry? (Common Voice Line)
                Can't stop, won't stop (Common Voice Line)
                Jackpot! (Common Voice Line)
                Hit me! (Common Voice Line)
                I could do this all day (Common Voice Line)
                Not hearing that noise (Common Voice Line)
                I'm on top of the world (Common Voice Line)
                Tinnitus (Common Voice Line)
                You gotta believe! (Common Voice Line)
                Roxo (Rare Skin)
                Laranja (Rare Skin)
                Vermelho (Rare Skin)
                Azul (Rare Skin)
                Synaesthesia (Epic Skin)
                Auditiva (Epic Skin)
                Ribbit (Legendary Skin)
                Hippityhop (Legendary Skin)
                Breakaway (Legendary Skin)
                Slapshot (Legendary Skin)
                Icon (Common Spray)
                Frog (Common Spray)
                Deck (Common Spray)
                Tag (Common Spray)
                Signature (Common Spray)
                Hero (Common Spray)
                Confident (Common Spray)
                Cereal (Common Spray)
                Scratch (Common Spray)
                Acelerar (Common Spray)
                Break It Down (Common Spray)
                In Concert (Common Spray)
                Wave (Common Spray)
                Walk of Fame (Common Spray)
                Bass (Common Spray)
                Vinyl (Common Spray)
                Grin (Common Spray)
                Under Control (Common Spray)
                Kambô (Common Spray)
                Spin (Common Spray)
                Baixo (Common Spray)
                Triplo (Common Spray)
                Mural (Common Spray)
        SUMMER_GAMES_2016 (7 items)
                Football (Rare Icon)
                Football (Common Spray)
                Be champions (Common Voice Line)
                Juggle (Epic Emote)
                Bicycle Kick (Epic Heroic Intro)
                Seleção (Legendary Skin)
                Striker (Legendary Skin)
        HALLOWEEN_2016 (3 items)
                Trick or Treat (Common Spray)
                R.I.P. (Rare Victory Pose)
                Killed it! (Common Voice Line)
`

var rawDataRegex = /Cosmetics for (.+)\.\.\.(\n.+)*/gm
var itemGroupRegex = / {8}(.+)(\n {16}(.+))*/gm
var data = []
var heroMatch
while ((heroMatch = rawDataRegex.exec(rawData)) !== null) {
  var rawItems = heroMatch[0].split('\n').slice(1).join('\n')
  var items = []
  var itemMatch
  while ((itemMatch = itemGroupRegex.exec(rawItems)) !== null) {
    items.push({
      group: itemMatch[1].split(' ')[0],
      items: itemMatch[0].split('\n').slice(1).map(a => a.trim())
    })
  }
  data.push({ hero: heroMatch[1], items })
}

var getClassForHero = hero => {
  switch (hero) {
    case "genji":
    case "mccree":
    case "pharah":
    case "reaper":
    case "soldier: 76":
    case "sombra":
    case "tracer":
      return "Assault"
    case "bastion":
    case "hanzo":
    case "junkrat":
    case "mei":
    case "torbjörn":
    case "widowmaker":
      return "Defence"
    case "d.va":
    case "reinhardt":
    case "roadhog":
    case "winston":
    case "zarya":
      return "Tank"
    case "ana":
    case "lúcio":
    case "mercy":
    case "symmetra":
    case "zenyatta":
      return "Support"
    default:
      return "Unknown"
  }
}

var getCleanID = name => name.toLowerCase().replace(/[öô]/g, 'o').replace('ú', 'u').replace('çã', 'ca').replace(/[^a-zA-Z 0-9]/g, '').replace(/ /g, '-')

var stupidNames = {
  "^_^": "joy",
  ">_<": "frustration",
  ";)": "winky-face"
}

var getType = type => {
  switch (type.toLowerCase().trim()) {
    case 'common voice line':
      return { quality: 'common', type: 'voice' }
    case 'legendary skin':
      return { quality: 'legendary', type: 'skins' }
    case 'rare skin':
      return { quality: 'rare', type: 'skins' }
    case 'epic skin':
      return { quality: 'epic', type: 'skins' }
    case 'common skin':
      return { quality: 'common', type: 'skins' }
    case 'common spray':
      return { quality: 'common', type: 'sprays' }
    case 'rare victory pose':
      return { quality: 'rare', type: 'poses' }
    case 'common victory pose':
      return { quality: 'common', type: 'poses' }
    case 'epic emote':
      return { quality: 'epic', type: 'emotes' }
    case 'common emote':
      return { quality: 'common', type: 'emotes' }
    case 'legendary emote':
      return { quality: 'legendary', type: 'emotes' }
    case 'rare icon':
      return { quality: 'rare', type: 'icons' }
    case 'epic heroic intro':
      return { quality: 'epic', type: 'intros' }
    case 'common heroic intro':
      return { quality: 'common', type: 'intros' }
    default:
      console.log("Unknown type?", type)
      return {}
  }
}

var heroes = {}
data.forEach(({ hero, items: itemGroups }) => {
  var heroID = getCleanID(hero)
  var heroData = {
    name: hero,
    class: getClassForHero(hero.toLowerCase()),
    id: heroID,
    items: {
      skins: [],
      emotes: [],
      intros: [],
      icons: [],
      sprays: [],
      voice: [],
      poses: []
    }
  }
  itemGroups.forEach(({ group, items }) => {
    items.forEach(item => {
      var [str, name, type] = item.match(/(.+) \((.+)\)/) //eslint-disable-line
      name = name.trim()
      if (name == 'RANDOM') return
      var id = getCleanID(name)
      id = id && id.length ? id : stupidNames[name] || "UNDEFINED"
      var { quality, type: itemType } = getType(type)
      if (!quality || !itemType) return
      var out = { name, id, quality: quality }
      switch (group) {
        case 'SUMMER_GAMES_2016':
        case 'HALLOWEEN_2016':
          out.event = group
          break;
        case 'ACHIEVEMENT':
          out.achievement = true
          break;
        case 'STANDARD_COMMON':
          out.standardItem = true
          break;
      }
      heroData.items[itemType].push(out)
    })
  })
  heroes[heroID] = heroData
})
