const OWL_DIVISIONS = {
  79: 'Atlantic',
  80: 'Pacific'
}

const OWLDATA = {
  dallas_fuel: {
    id: "dallas_fuel",
    abbreviation: "DAL",
    location: "Dallas",
    name: "Fuel",
    display_name: "Dallas Fuel",
    home_location: "Dallas, TX",
    division: OWL_DIVISIONS[80],
    description: "In addition to paying tribute to the region's strong heritage in the energy sector, the team name and the flame in the logo also symbolize the galvanizing spark that the franchise is looking to ignite among esports fans in Dallas. The Fuel's colors will be familiar to fans of the team's owner, Team Envy, whose players are known in other esports as the \"Boys in Blue.\" ",
    colors: {
      primary: "#032340",
      secondary: "#0072CE",
      tertiary: "#9EA2A2"
    }
  },
  philadelphia_fusion: {
    id: "philadelphia_fusion",
    abbreviation: "PF",
    location: "Philadelphia",
    name: "Fusion",
    display_name: "Philadelphia Fusion",
    home_location: "Philadelphia, PA",
    division: OWL_DIVISIONS[79],
    description: "We're excited to announce the Philadelphia Fusion, a team whose name and logo reflect the velocity, dynamism, and creative energy that is generated by bringing distinct parts together to produce something new. The orange and black of the Fusion's team colors have a special place in the heart of Philadelphia sports fans, as they are also the official colors of the professional ice hockey team known as the Philadelphia Flyers (which is also owned by the Fusion's parent company).",
    colors: {
      primary: "#FF9E1B",
      secondary: "#000000",
      tertiary: "#FFFFFF"
    }
  },
  houston_outlaws: {
    id: "houston_outlaws",
    abbreviation: "HO",
    location: "Houston",
    name: "Outlaws",
    display_name: "Houston Outlaws",
    home_location: "Houston, TX",
    division: OWL_DIVISIONS[79],
    description: "Texas is famous for its hardy, self-reliant cowboy culture, where people live by their own rules. The team name references this rebellious streak, and the star, longhorn skull, and twin revolvers in the team logo are also emblematic of the Lone Star State. Last but not least, the green in the team's colors is a signature shade for Outlaws parent organization OpTic Gaming, whose rabid fans are collectively known as \"the Green Wall.\"",
    colors: {
      secondary: "#000000",
      primary: "#97D700",
      tertiary: "#FFFFFF"
    }
  },
  boston_uprising: {
    id: "boston_uprising",
    abbreviation: "BOS",
    location: "Boston",
    name: "Uprising",
    display_name: "Boston Uprising",
    home_location: "Boston, MA",
    division: OWL_DIVISIONS[79],
    description: "The name Boston Uprising was selected to represent the resilience of the region’s revolutionary forefathers, whose indomitable legacy laid the foundation for the great city of Boston. The Boston Uprising colors will be blue, yellow and black, with the blue and yellow tones representing the colors of Boston’s official flag. The team logo is a protective shield encompassing an emboldened letter B, which has become synonymous with the city.",
    colors: {
      primary: "#174B97",
      secondary: "#EFDF00",
      tertiary: "#000000"
    }
  },
  "new-york_excelsior": {
    id: "new-york_excelsior",
    abbreviation: "NYE",
    location: "New York",
    name: "Excelsior",
    display_name: "New York Excelsior",
    home_location: "New York City, NY",
    division: OWL_DIVISIONS[79],
    description: "The name Excelsior means “ever upward” in Latin, and is inspired by the everyday heroism of New York. It's this spirit of optimism, drive, and ambition that the team hopes will propel them to victory in the Overwatch League. The team nickname, “NYXL,” also evokes New York at its strongest, while the flag logo represents different people, cultures, and ideas coming together",
    colors: {
      primary: "#171C38",
      secondary: "#0F57EA",
      tertiary: "#FF1C26"
    }
  },
  "san-francisco_shock": {
    id: "san-francisco_shock",
    abbreviation: "SFS",
    location: "San Francisco",
    name: "Shock",
    display_name: "San Francisco Shock",
    home_location: "San Francisco, CA",
    division: OWL_DIVISIONS[80],
    description: "The Shock's logo references parts of San Francisco's past and present that are as vivacious as the bright orange of the city's famous Golden Gate Bridge. The seismograph waves and the name evoke the region's earthquake activity, while its gold color hearkens back to San Francisco's origins in the California gold rush of the 1800s.",
    colors: {
      primary: "#FC4C02",
      secondary: "#75787B",
      tertiary: "#CAB64B"
    }
  },
  "los-angeles_valiant": {
    id: "los-angeles_valiant",
    abbreviation: "VAL",
    location: "Los Angeles",
    name: "Valiant",
    display_name: "Los Angeles Valiant",
    home_location: "Los Angeles, CA",
    division: OWL_DIVISIONS[80],
    description: "City of Angels. City of Champions. City of the Valiant. This is LA and we are its newest ambassadors: The Los Angeles Valiant.\r\nThe roster is as diverse as the city it represents. Our players embody what it means to be Valiant: fearless, determined, and noble citizens. This is who we are and who we always strive to be. Our commitment is to you: our fans and our city. We pledge an experience unlike any other. We will compete hard to earn your support.\r\nThis is LA. We are The Valiant.",
    colors: {
      primary: "#4A7729",
      secondary: "#000000",
      tertiary: "#D9C756"
    }
  },
  "los-angeles_gladiators": {
    id: "los-angeles_gladiators",
    abbreviation: "GLA",
    location: "Los Angeles",
    name: "Gladiators",
    display_name: "Los Angeles Gladiators",
    home_location: "Los Angeles, CA",
    division: OWL_DIVISIONS[80],
    description: "The team is named for the fighters of ancient Rome, who were renowned for their ferocity and power; the roaring lion and battle-hardened shield also symbolize these qualities. The lion figure echoes the logo of the LA Rams, the pro football team owned by Gladiators owners Stan and Josh Kroenke. And the team colors, purple and white, reference the royal colors of the Roman emperors, to whom the gladiators dedicated their exploits.",
    colors: {
      primary: "#3C1053",
      secondary: "#000000",
      tertiary: "#FFFFFF"
    }
  },
  florida_mayhem: {
    id: "florida_mayhem",
    abbreviation: "FM",
    location: "Florida",
    name: "Mayhem",
    display_name: "Florida Mayhem",
    home_location: "Florida",
    division: OWL_DIVISIONS[79],
    description: "Florida is well known for its beaches and cheerful culture, and the \"Sunshine State\" nickname is repped by the bright yellow in the Mayhem's colors. The red is an homage to the colors of Misfits Gaming, the parent organization of Florida Mayhem, which is heralded for its track record in competitive Overwatch and other titles. Lastly, the bomb and palm tree in the logo shout out the Florida landscape and the Mayhem's \"explosive\" playstyle",
    colors: {
      primary: "#FEDB00",
      secondary: "#AF272F",
      tertiary: "#000000"
    }
  },
  shanghai_dragons: {
    id: "shanghai_dragons",
    abbreviation: "SHD",
    location: "Shanghai",
    name: "Dragons",
    display_name: "Shanghai Dragons",
    home_location: "Shanghai",
    division: OWL_DIVISIONS[80],
    description: "The dragon and the color red were chosen as themes in the team's logo because they resonate with Chinese culture and history.",
    colors: {
      primary: "#D22630",
      secondary: "#000000",
      tertiary: "#FCE300"
    }
  },
  seoul_dynasty: {
    id: "seoul_dynasty",
    abbreviation: "SEO",
    location: "Seoul",
    name: "Dynasty",
    display_name: "Seoul Dynasty",
    home_location: "Seoul",
    division: OWL_DIVISIONS[80],
    description: "While the name certainly evokes images of Asian rulers in bygone eras, it's also a term in traditional sports, reserved only for those teams whose names become indelibly associated with long-term success—a distinction this team is clearly aiming for. As for the logo, the tiger is a national symbol of South Korea, representing strength, courage, and good fortune, while the golden color emphasizes the connection to royalty.",
    colors: {
      secondary: "#AA8A00",
      primary: "#000000",
      tertiary: "#FFFFFF"
    }
  },
  london_spitfire: {
    id: "london_spitfire",
    abbreviation: "LS",
    location: "London",
    name: "Spitfire",
    display_name: "London Spitfire",
    home_location: "London",
    division: OWL_DIVISIONS[79],
    description: "The Supermarine Spitfire was the name of a British fighter plane that was flown in the Royal Air Force, most famously during the Battle of Britain in World War II, and it is this spirit of bravery under fire that imbues the team's identity. The light blue of the logo's background is the blue of Cloud9, London Spitfire’s parent organization, which has a storied history in Western esports. The Spitfire itself and the orange of the team's colors are a nod to Lena “Tracer” Oxton, the British Overwatch® hero who was a member of the RAF in the game’s lore.",
    colors: {
      secondary: "#FF8200",
      primary: "#59CBE8",
      tertiary: "#1C2B39"
    }
  }
}

module.exports = OWLDATA
